### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by luciagrami** [tseemann/snp-dists#14] opened 2018-02-19 22:20 UTC
Hello,  I am trying to run snp-dist (thank you very much for this tool!) in Ubintu 14.04, and i'm getting this error:

This is snp-dists 0.4 
Segmentation fault (core dumped)

Apparently it could mean the software tries to access memory and it has no permission, so i tried to solve this with:
ulimit -c unlimited
but the problem persists.

Can you help me with this? Could it be an instalation problem?
Thanks

**Comment by andersgs** [comment] 2018-02-19 22:22
Hi @luciagrami. It would help if you could provide us with an example dataset in order to reproduce the problem.

Thank you.

Anders.

**Comment by luciagrami** [comment] 2018-02-19 22:50
Ok, I am trying to create the SNP distances matrix from this concatenated alignment of core genes from a set of closley related bacterial isolates.
Thanks!

[ConcaAlignSGF.fasta.tar.gz](https://github.com/tseemann/snp-dists/files/1738410/ConcaAlignSGF.fasta.tar.gz)

**Comment by andersgs** [comment] 2018-02-20 05:51
Hi @luciagrami. Looking into it, thank you. In the meantime, I was able to generate the SNP matrix with the stable release (https://github.com/tseemann/snp-dists/releases/tag/v0.2). Give that one a go, if you can. A.

**Comment by luciagrami** [comment] 2018-02-20 15:46
stable release worked! Thanks

**Comment by kloetzl** [comment] 2018-02-21 10:12
I would say, this is a duplicate of #9.

**Comment by tseemann** [comment] 2018-04-22 05:51
Agreed.

**Closed by tseemann** 2018-04-22 05:51 UTC
